import type { Imovel } from '../types/api';

// Lista de imóveis e empreendimentos estáticos em diferentes estados
const imoveisEstaticos: Imovel[] = [
    // --- Imóveis em Pernambuco ---
    {
        idImv: 1,
        idEmpreendimento: null,
        isEmpreendimento: false,
        codigoImovel: "RECIFE_CASA_01",
        nomeImovel: "Casa Ampla em Casa Forte",
        nomeEmpresa: "Particular",
        preco: 2500000,
        latitude: -8.033620,
        longitude: -34.912957,
        urlFotoDestaque: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        urlFicha: 'https://app.reaisystems.com.br/imovel/fichaPublica/RECIFE_CASA_01',
        tipo: "Residencial",
        subTipo: "Casa",
        unidadesDisponiveis: 1,
        unidadesTotal: 1,
        quartos: 4,
        areaUtil: 320,
        areaTotal: 320,
        vgv: 2500000,
        estagio: "Pronto para Morar",
    },
    {
        idImv: 2,
        idEmpreendimento: 1,
        isEmpreendimento: true,
        codigoImovel: "RECIFE_EMP_01",
        nomeImovel: "Bons Ventos",
        nomeEmpresa: "A&B Engenharia",
        preco: 177550,
        latitude: -8.040180,
        longitude: -34.908350,
        urlFotoDestaque: "https://images.pexels.com/photos/280221/pexels-photo-280221.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        urlFicha: 'https://app.reaisystems.com.br/imovel/fichaPublica/RECIFE_EMP_01',
        tipo: "Residencial",
        subTipo: "Apartamento",
        unidadesDisponiveis: 0,
        unidadesTotal: 48,
        quartos: 3,
        areaUtil: 57,
        areaTotal: 57,
        vgv: 8520000,
        estagio: "Em Construção",
    },
    // --- Imóveis no Ceará ---
    {
        idImv: 3,
        idEmpreendimento: null,
        isEmpreendimento: false,
        codigoImovel: "FORTALEZA_CASA_01",
        nomeImovel: "Casa de Praia em Meireles",
        nomeEmpresa: "Particular",
        preco: 3100000,
        latitude: -3.723049,
        longitude: -38.487843,
        urlFotoDestaque: "https://images.pexels.com/photos/164558/pexels-photo-164558.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        urlFicha: 'https://app.reaisystems.com.br/imovel/fichaPublica/FORTALEZA_CASA_01',
        tipo: "Residencial",
        subTipo: "Casa",
        unidadesDisponiveis: 1,
        unidadesTotal: 1,
        quartos: 5,
        areaUtil: 450,
        areaTotal: 450,
        vgv: 3100000,
        estagio: "Pronto",
    },
    {
        idImv: 4,
        idEmpreendimento: 2,
        isEmpreendimento: true,
        codigoImovel: "FORTALEZA_EMP_01",
        nomeImovel: "Torres do Cocó",
        nomeEmpresa: "Construtora Ceará",
        preco: 980000,
        latitude: -3.748366,
        longitude: -38.488344,
        urlFotoDestaque: "https://images.pexels.com/photos/210617/pexels-photo-210617.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        urlFicha: 'https://app.reaisystems.com.br/imovel/fichaPublica/FORTALEZA_EMP_01',
        tipo: "Residencial",
        subTipo: "Apartamento",
        unidadesDisponiveis: 30,
        unidadesTotal: 120,
        quartos: 3,
        areaUtil: 110,
        areaTotal: 110,
        vgv: 117000000,
        estagio: "Lançamento",
    },
    {
        idImv: 5,
        idEmpreendimento: 3,
        isEmpreendimento: true,
        codigoImovel: "JUAZEIRO_EMP_01",
        nomeImovel: "Residencial Padre Cícero",
        nomeEmpresa: "Cariri Empreendimentos",
        preco: 350000,
        latitude: -7.213234,
        longitude: -39.317531,
        urlFotoDestaque: "https://images.pexels.com/photos/221024/pexels-photo-221024.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        urlFicha: 'https://app.reaisystems.com.br/imovel/fichaPublica/JUAZEIRO_EMP_01',
        tipo: "Residencial",
        subTipo: "Apartamento",
        unidadesDisponiveis: 45,
        unidadesTotal: 80,
        quartos: 2,
        areaUtil: 65,
        areaTotal: 65,
        vgv: 28000000,
        estagio: "Na Planta",
    },
    // --- Imóveis na Paraíba ---
    {
        idImv: 6,
        idEmpreendimento: null,
        isEmpreendimento: false,
        codigoImovel: "JOAOPESSOA_CASA_01",
        nomeImovel: "Apartamento em Tambaú",
        nomeEmpresa: "Particular",
        preco: 890000,
        latitude: -7.116538,
        longitude: -34.825226,
        urlFotoDestaque: "https://images.pexels.com/photos/277667/pexels-photo-277667.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        urlFicha: 'https://app.reaisystems.com.br/imovel/fichaPublica/JOAOPESSOA_CASA_01',
        tipo: "Residencial",
        subTipo: "Apartamento",
        unidadesDisponiveis: 1,
        unidadesTotal: 1,
        quartos: 3,
        areaUtil: 130,
        areaTotal: 130,
        vgv: 890000,
        estagio: "Pronto",
    },
    {
        idImv: 7,
        idEmpreendimento: 4,
        isEmpreendimento: true,
        codigoImovel: "CAMPINAGRANDE_EMP_01",
        nomeImovel: "Mirante da Borborema",
        nomeEmpresa: "Engenharia PB",
        preco: 550000,
        latitude: -7.222730,
        longitude: -35.881478,
        urlFotoDestaque: "https://images.pexels.com/photos/1115804/pexels-photo-1115804.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        urlFicha: 'https://app.reaisystems.com.br/imovel/fichaPublica/CAMPINAGRANDE_EMP_01',
        tipo: "Residencial",
        subTipo: "Apartamento",
        unidadesDisponiveis: 80,
        unidadesTotal: 90,
        quartos: 3,
        areaUtil: 88,
        areaTotal: 88,
        vgv: 49500000,
        estagio: "Em Construção",
    },
];

export async function buscarImoveisEstaticos(termo: string): Promise<Imovel[]> {
    const termoBusca = termo.toLowerCase().trim();
    if (!termoBusca) {
        return imoveisEstaticos;
    }
    return imoveisEstaticos.filter(imovel =>
        imovel.nomeImovel.toLowerCase().includes(termoBusca) ||
        imovel.nomeEmpresa.toLowerCase().includes(termoBusca) ||
        imovel.codigoImovel.toLowerCase().includes(termoBusca)
    );
}